name: Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 1 minutes

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: curl -X GET https://dantime.vercel.app/api/monitor
