name: Cron Job

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: curl -X GET https://dantime.vercel.app/api/monitor
